### PR TITLE
[Excel 2003 XML] Add support for font colors + required fixes

### LINKED ISSUE #33: Some fields (StyleID, Formula, Index) not read using namespace
[This block](https://github.com/roo-rb/roo-xls/blob/6449b5de121420cb8981df876acf984b547d7703/lib/roo/xls/excel_2003_xml.rb#L200-L215) has references to fields that aren't using the `${namespace}:` prefix. This breaks the style reading completely, but should be a relatively easy fix.

### LINKED ISSUE #41: [Excel 2003 XML] No documentation that 'expand_merged_ranges' unsupported
See https://github.com/roo-rb/roo#expand_merged_ranges

Probably would be best to just mention this in the README?

### PR DESCRIPTION
**Pull request by ms-ati**
As mentioned in #42, all I'd needed was to add support for the color of a given cell. But unfortunately, I discovered that other pieces of the puzzle were broken along the way.

This PR attempts to fix all that, adding the support for fonts and colors via `#font`.

Adds RSpec coverage via the following test files (screenshot included for those without Excel):
[font_colors.xml.zip](https://github.com/roo-rb/roo-xls/files/1729458/font_colors.xml.zip)

font_colors_screenshot_in_mac_excel_16 10

Fixes #41, #42, #43, #44 

Also fixes #33 I believe

### CODE REVIEW

**Comment by ms-ati** [comment]
Following [semantic versioning](https://semver.org/), I recommend bumping a MINOR version, to `1.2.0` after this PR is merged, as this code adds new capability (font name, size, and color) into an existing API, and fixes existing bugs.

However -- there may be users depending on the mis-parsing of the cells, especially row and column numbers around merged cells. Therefore, you may need to bump a MAJOR version, to `2.0.0`, to reflect incompatible changes for some users.

Does that make sense? Depends how you all are thinking about it.

**Comment by ms-ati** [comment]
@Empact et all -- any chance of getting eyes on this PR?

**Comment by Empact** [comment]
This looks great. Thanks! Keep the PRs coming. :)

**Comment by ms-ati** [comment]
Hurray! Thanks @Empact. I might try to tackle the streaming api question, now that you mention it. In the meantime -- our team would really appreciate it if you could cut a gem release that contains this PR?

Cheers!

-Marc

**Comment by ms-ati** [comment]
Ping on request for a `roo-xls` gem release @Empact ?

**Comment by Empact** [comment]
@ms-ati Released! Could you give it a try? https://rubygems.org/gems/roo-xls/versions/1.2.0

Also a github release https://github.com/roo-rb/roo-xls/releases/tag/v1.2.0

**Comment by ms-ati** [comment]
Nice @Empact ! Thank you :)

**Pull request merged**
